---
- name: Install haproxy
  package:
    name: haproxy
    state: present
- name: debug line
  debug:
    var: hostvars['10.239.21.16']
- name: haproxy config
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  register: haproxy_config
- name: restart haproxy
  service:
    name: haproxy
    enabled: true
    state: restarted
  when: haproxy_config.changed
