---
- hosts: rhntest
  become: true
  tasks:
    - name: test rhn
      command: yum repolist
      register: yum_repolist
    - name: check if repolist update needed
      command: whoami
      when: yum_repolist | search("repolist: 0")
