---
- name: test rhn
  command: yum repolist
  args:
    warn: false
  register: yum_repolist
- name: write script template
  template: 
    src: templates/rhnregister.sh.j2
    dest: /root/.rhnregister.sh
    mode: 0750
  when: "'repolist: 0' in yum_repolist.stdout"
- name: execute rhn registration
  command: /bin/bash /root/.rhnregister.sh
  when: "'repolist: 0' in yum_repolist.stdout"
- name: delete registration script
  file: 
    path: /root/.rhnregister.sh
    state: absent
